# Generated by Django 4.2.2 on 2023-07-04 14:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
