# Generated by Django 4.2.2 on 2023-07-04 17:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
